apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
  {{- include "nginx.labels" . | nindent 4 }}
data:
  {{ .Values.config.name }}: |
  {{- toYaml .Values.config.data | nindent 4 }}