{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  {{- include "nginx.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.hpa.maxreplicas }}
  minReplicas: {{ .Values.hpa.minrplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: {{ .Values.hpa.cpu_uti }}
{{- end -}}